debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.servlet: info
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
springdoc:
  show-actuator: true
spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
  application.name: orury-common
  datasource:
    url: ${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER_NAME}
    password: ${LOCAL_DB_USER_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  flyway:
    enabled: true
    url: ${LOCAL_DB_NAME}
    user: ${LOCAL_DB_USER_NAME}
    password: ${LOCAL_DB_USER_PASSWORD}
    schemas: flyway
    locations: classpath:/db/migration
    baseline-version: 1
    baseline-on-migrate: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
    prefix=file: src/main/resources/templates/
---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb