server.port: 8080
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    
    org.springframework.web.servlet: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
springdoc:
  show-actuator: true
spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
  application.name: orury-admin
  datasource:
    url: ${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER_NAME}
    password: ${LOCAL_DB_USER_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
    baseline-on-migrate: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
    prefix=file: src/main/resources/templates/
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          kakao:
  #            client-id: ${KAKAO_OAUTH_CLIENT_ID}
  #            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
  #            authorization-grant-type: authorization_code
  #            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
  #            client-authentication-method: client_secret_post
  #        provider:
  #          kakao:
  #            authorization-uri: https://kauth.kakao.com/oauth/authorize
  #            token-uri: https://kauth.kakao.com/oauth/token
  #            user-info-uri: https://kapi.kakao.com/v2/user/me
  #            user-name-attribute: id

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #  echo org-fastcampus-orury-core-api-admin-batch-org-fastcampus-orury-core-api-admin-batch | base64
  secret: b3JnLWZhc3RjYW1wdXMtb3J1cnktY29yZS1hcGktYWRtaW4tYmF0Y2gtb3JnLWZhc3RjYW1wdXMtb3J1cnktY29yZS1hcGktYWRtaW4tYmF0Y2gK
  token-validity-in-seconds: 86400
---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb